services:
#  db:
#    image: postgres:12
#    restart: always
#    environment:
#      POSTGRES_PASSWORD: admin
#      POSTGRES_USER: admin
#      POSTGRES_DB: postgres
#    ports:
#      - 5432:5432
#  mongodb:
#    image: mongo
#    container_name: mongodb
#    ports:
#      - 27017:27017
#    restart: unless-stopped
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379