version: '3'

services:
  app:
    build:
      context: .
    restart: always
    depends_on:
      - postgres
    ports:
      - 8080:8080
    networks:
      - backend

  postgres:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: postgres
    expose:
      - 5432
    networks:
      - backend

networks:
  backend:
    driver: bridge