version: '3'

services:
  app:
    build:
      context: .
    ports:
      - 8080:80




#  db:
#    image: postgres:12
#    restart: always
#    environment:
#      POSTGRES_PASSWORD: admin
#      POSTGRES_USER: admin
#      POSTGRES_DB: postgres
#    ports:
#      - 5432:5432